language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.5-dev
- pypy
- pypy3
- nightly

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: RUN_LINTS=true

cache: pip

install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="2.6.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        pip install -r requirements.txt --upgrade
      fi
before_install: 'if [ "$RUN_LINTS" = "true" ]; then pip install pre-commit; fi'
script: 'if [ "$RUN_LINTS" = "true" ]; then pre-commit run --all-files; else bash -xe travis/unit-tests.sh; fi'
