language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- 3.5-dev
- pypy
- pypy3
- nightly

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: RUN_LINTS=true

cache: pip

before_install:
  - |
      case "$TRAVIS_PYTHON_VERSION" in
        pypy) export PYPY_VERSION="pypy-2.6.1" ;;
        pypy3) export PYPY_VERSION="pypy3.3-5.5-alpha" ;;
      esac
      if ! [ -z "$PYPY_VERSION" ] ; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        "$PYENV_ROOT/bin/pyenv" install "$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/$PYPY_VERSION/bin/python" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
      if [ "$RUN_LINTS" = "true" ]; then
        pip install pre-commit
      else
        pip install codeclimate-test-reporter coverage nose pytest
      fi
script: 
  - |
      if [ "$RUN_LINTS" = "true" ] ; then
        pre-commit run --all-files
      else
        coverage run --include='*string_generator.py' -m pytest
        codeclimate-test-reporter
      fi
